name: gudang
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  qr_flutter: ^4.0.0
  flutter: 
    sdk: flutter
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  flutter_zoom_drawer: ^3.1.1
  flutter_barcode_scanner: ^2.0.0
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - image/
    